services:
  cassandra:
    image: cassandra:4.1
    container_name: thehive-cassandra
    restart: unless-stopped
    environment:
      - MAX_HEAP_SIZE=512M
      - HEAP_NEWSIZE=128M
      - CASSANDRA_CLUSTER_NAME=thehive
    volumes:
      - cassandra-data:/var/lib/cassandra
    networks:
      - thehive-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.24
    container_name: thehive-elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - thehive-net

  thehive:
    image: strangebee/thehive:5.4
    container_name: thehive
    restart: unless-stopped
    depends_on:
      - cassandra
      - elasticsearch
    ports:
      - "9000:9000"
    command:
      - --cql-hostnames
      - cassandra
      - --index-backend
      - elasticsearch
      - --es-hostnames
      - elasticsearch
      - --no-config-cortex
      - --secret
      - "${THEHIVE_SECRET}" # openssl rand -hex 32 (minimum 256 bits requis)
    volumes:
      - thehive-data:/opt/thp/thehive/files
    networks:
      - thehive-net

networks:
  thehive-net:
    driver: bridge

volumes:
  cassandra-data:
  es-data:
  thehive-data:
